dist: xenial
language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.torch/models
python:
 - "3.5"
 - "3.6"
 - "3.7"
install:
 - pip install --upgrade pip setuptools
 - "pip install --upgrade .[test]"
 - node -v
 - npm install
 - npm run build
 # prefetch model
 - mkdir -p ~/.torch/models
 - cd ~/.torch/models; wget -nc https://storage.googleapis.com/openpifpaf-pretrained/v0.5.0/resnet50block5-pif-paf-edge401-190424-122009-f26a1f53.pkl; cd -
script:
 - pylint openpifpafwebdemo --disable=fixme
 - npm run lint
 - npm run test
