apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: default
data:
  tls.crt: base64 encoded cert  # cat mycert.crt | base64 -w0
  tls.key: base64 encoded key
type: kubernetes.io/tls
